/**
 * Defines a Redux slice for managing posts with initial state and reducers.
 * 
 * The slice includes:
 * - An initial state with predefined posts.
 * - A reducer `postAdded` to add new posts, utilizing a `prepare` function
 *   to structure the payload with a unique ID generated by `nanoid`.
 * 
 * Exports:
 * - `selectAllPosts`: A selector function to retrieve all posts from the state.
 * - `postAdded`: An action creator for adding a new post.
 * - The slice reducer as the default export.
 */
import { createSlice, nanoid } from '@reduxjs/toolkit';

const initialState = [
    { id: '1', title: 'Learning Redux Toolkit', content: "I've heard good things." },
    { id: '2', title: 'Slices...', content: "The more I say slice, the more I want pizza." }
]

const postsSlice = createSlice({
    name: 'posts',
    initialState,
    reducers: {
        postAdded: {
            reducer(state, action) {
                state.push(action.payload)
            },
            prepare(title, content, userid) {
                return {
                    payload: {
                        id: nanoid(),
                        title,
                        content,
                        userid
                    }
                }
            }
        }
    }
})

export const selectAllPosts = (state) => state.posts;

export const { postAdded } = postsSlice.actions

export default postsSlice.reducer